* TODOs for the project

17 - 22 HRS

** TODO Create basic grid for homepage
** TODO Add basic header and footer
** TODO Homepage with list of articles' categories
** DONE Write basic tests
** DONE Start working in the user simple session

* Not mandatory TODOs

** Add validation to only vote once per category

* Tasks from Reviewers

- [ ] See my article when I click on the new category. 
- [ ] After I vote the word should change to unvote
- [ ] I should not be able to vote more than 1
- [ ] Use RESTFUL routes, for example, the category you do not need all of them because the user does not have the possibility to create a new article
- [ ] Your page extends too much to the right.
- [ ] Any user is able to edit any post even without logging in, the only user to edit a post should be a user who created the same article.
- [ ] Any user can create a post even before login, this should not be the case, only a logged-in user should have access to the create article form.
- [ ] The articles table should have author_id, currently, it has user_id.
- [ ] Please remove commented code from views, routes.rb.
- [ ] Please make sure that the user should not be able to create an article if he is not authenticated.
- [ ] Please add integration tests for authentication and other browser features e.g create an article.
- [ ] You should follow the design provided and use the same color schemes.
- [ ] Please use assets pipeline located `app/assets/stylesheets for all of your CSS stylesheets.
- [ ] I would suggest to give more styling to the form that creates articles
- [ ] Views should be completely separate from app logic. You can move all view-related logic to app/helpers.
- [X] A user can't log out because the logout link is unavailable in the app.
- [X] Only the user that creates the article should be able to edit it. Currently, any user can edit your posts
- [X] User should be able to sign out
